#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit on command errors and treat unset variables as an error
set -eu

ynh_abort_if_errors	# Active trap to stop the script if an error is detected.

ynh_clean_setup () {
	# Clean installation residues that are not supported by the remove script.
	# Clean hosts
	echo ""
}

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
token_telegram=$YNH_APP_ARG_TOKEN_TELEGRAM

# Final path is the classic name for "where we will put the source of the app"
final_path=/var/www/$app

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..." --weight=1

# Check final_path availability
test ! -e "$final_path" || ynh_die "$final_path already exists, aborting"

# Register (book) the web path
# not needed ynh_webpath_register $app $domain $path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_script_progression --message="Storing installation settings..." --weight=1

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path
ynh_app_setting_set $app token_telegram $token_telegram

# Create system user dedicace for this app
ynh_system_user_create $app

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Creates the destination directory and stores its location.
sudo mkdir "$final_path"
ynh_app_setting_set $app final_path $final_path

ynh_script_progression --message="Install python packages..." --weight=1

ynh_package_install python3-pip

# Install de library Python
sudo pip3 install python-telegram-bot
sudo pip3 install certifi
sudo pip3 install urllib3[secure]
sudo pip3 install PySocks
sudo pip3 install emoji
sudo pip3 install facebook_scraper

ynh_script_progression --message="Create files..." --weight=1

sudo cp ../conf/config.py $final_path
sudo cp ../conf/chatbot.py $final_path
sudo sed -i "s@__TOKEN_TELEGRAM__@${token_telegram}@g" "${final_path}/config.py"
sudo touch ${final_path}/fbpages.csv

# Set permissions spip directory
sudo chown -R $app: $final_path

# Install systemd script
sudo cp ../conf/telegram.chatbot.service /etc/systemd/system/$app.service
sudo chown root: /etc/systemd/system/$app.service
sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/systemd/system/$app.service
sudo sed -i "s@__APP__@$app@g" /etc/systemd/system/$app.service

# Create log directory
sudo mkdir /var/log/$app/

# Start service auto
sudo systemctl daemon-reload
sudo systemctl enable $app.service
sudo systemctl start $app.service

sudo yunohost service add $app -l /var/log/$app/$app.log

sudo cp -a ../conf/dist $final_path

sudo chown $app: /var/log/$app/

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring nginx web server..." --weight=1

# Create a dedicated nginx config
ynh_add_nginx_config


#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading nginx web server..." --weight=1

ynh_systemd_action --action=reload --service_name=nginx

ynh_script_progression --message="Installation of $app completed" --last
