#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)
final_path=$(ynh_app_setting_get "$app" final_path)

#=================================================
# REMOVE THE MAIN DIR OF THE APP
#=================================================
ynh_script_progression --message="Removing app main directory..." --weight=1

# Stop telegram.chatbot service
if [ -e "/etc/systemd/system/${app}.service" ]; then
	echo "Delete systemd script"
	sudo service $app stop
	sudo rm "/etc/systemd/system/${app}.service"
	sudo systemctl disable $app.service
fi

# Remove monitoring service Yunohost.
if sudo yunohost service status | grep -q $app
then
	echo "Remove ${app} service"
	sudo yunohost service remove $app
fi

ynh_secure_remove "/opt/${app}"
ynh_secure_remove "/var/log/${app}"

# Remove user
ynh_system_user_delete $app

# Remove sources
ynh_secure_remove --file="$final_path"

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing nginx web server configuration..." --weight=1

ynh_remove_nginx_config
ynh_systemd_action --action=reload --service_name=nginx

ynh_script_progression --message="Removal of $app completed" --last

